{
 "title": "Internet Speed Test",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "fields_value",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"fields_value\" / 125000 FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "fields_value",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"fields_value\" / 125000 FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "fields_up",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"fields_up\" / 125000 FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "fields_up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "fields_up",
     "measurement": "mqtt_consumer",
     "query": "SELECT \"fields_up\" / 125000 FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "fields_up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "fields_latency",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "fields_latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "fields_latency",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "fields_latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Jitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "fields_jitter",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "fields_jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "fields_jitter",
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "fields_jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Tests",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT \"fields_value\" /125000 AS \"Download (Mbps)\", \"fields_up\" /125000 AS \"Upload (Mbps)\",  \"fields_latency\" AS \"Latency (ms)\", \"fields_jitter\" AS \"Jitter (ms)\" FROM \"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "fields_up" ], "type": "field" },
       { "params": [ "Upload" ], "type": "alias" }
      ],
      [
       { "params": [ "fields_value" ], "type": "field" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "fields_jitter" ], "type": "field" },
       { "params": [ "Jitter" ], "type": "alias" }
      ],
      [
       { "params": [ "fields_latency" ], "type": "field" },
       { "params": [ "Latency" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "panels": [
    {
     "title": "Latency",
     "targets": [
      { "expr": "fields_latency" }
     ]
    },
    {
     "title": "Jitter",
     "targets": [
      { "expr": "fields_jitter" }
     ]
    },
    {
     "title": "Temps Mitjà",
     "targets": [
      { "expr": "temps_mitja" }
     ]
    },
    {
     "title": "Paquets Enviats",
     "targets": [
      { "expr": "paquets_enviats" }
     ]
    },
    {
     "title": "Paquets Perduts",
     "targets": [
      { "expr": "paquets_perduts" }
     ]
    }
   ]
  }
 ]
}